### ISSUE TITLE
create an example Workflow (Github Action) for running sqlfmt in CI

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/sqlfmt-docs#11]
Should include two examples:
1. Simple check workflow
2. Format-and-commit workflow

Also consider packaging this as an Action.

**Comment by sgoley** [comment]
+1 for this! 
Was trying to look at the possibility of doing something like the "Drizly" workflow described [here](https://github.com/sqlfluff/sqlfluff-github-actions/tree/main/menu_of_workflows/drizly) of getting all the sqlfmt changes as annotations to be accepted / rejected in the PR workflow action.

Unfortunately my current team is divided between VS code users (who can use the pre-commit sqlfmt execute) and dbt Cloud IDE users.... who I dont believe have the ability to manage the environment to the enable the "run on save" or "run pre-commit" by default.

Thanks!

**Comment by sgoley** [comment]
Came up with this as a basic workflow action to run the entire models directory on each run. 
Working on a variation of this for changed files only.

And dont worry about defining the `secrets.GITHUB_TOKEN` - its automatically created by github for the github action workflow.

``` yml
# GitHub Action that uses sqlfmt to reformat the sql in an incoming pull request.
# If all sql in the pull request is compliant with sqlfmt then this Action does nothing.
# Otherwise, sqlfmt is run and its changes are committed back to the incoming pull request.

name: autosqlfmt
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install sqlfmt
        run: pip install shandy-sqlfmt[jinjafmt]
      - name: if needed, commit sqlfmt changes to the pull request
        run: |
          sqlfmt models/.
          git config --global user.name 'autosqlfmt'
          git config --global user.email 'autosqlfmt@github.com'
          git remote set-url origin https://x-access-token/:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: format sql with sqlfmt"
          git push
 ```
